name: Test with Flaky Report

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Install Dependencies
        run: go mod tidy

      - name: Run Tests with gotestsum
        run: |
          go install gotest.tools/gotestsum@latest
          gotestsum --junitfile test-report.xml --format short-verbose ./...

      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: test-report.xml

      - name: Generate Flaky Test Report
        uses: ctrf-io/github-test-reporter@v1
        with:
          flaky-threshold: 2
          junit-file: test-report.xml
