name: Test with Flaky Report

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Install Dependencies
        run: go mod tidy

      - name: Install gotestsum
        run: go install gotest.tools/gotestsum@latest

      - name: Run Tests and Log Output
        run: |
          gotestsum \
          --format=github-actions \
          --rerun-fails --rerun-fails=10 --rerun-fails-max-failures=10 \
          --packages="./..." -- -count=1 | tee /tmp/full_output.log
          exit_code=${PIPESTATUS[0]}
          [ $exit_code -ne 0 ] && exit $exit_code
          sed 's/\x1b\[[0-9;]*m//g' /tmp/full_output.log | awk '/=== Failed/ {found=1} found' > /tmp/raw_output.log
          go run tools/flaky_test_report/main.go < /tmp/raw_output.log > flaky_report.json

      - name: Generate PR Comment
        if: success()
        run: |
          go run tools/generate_pr_comment/main.go < flaky_report.json

      - name: Comment on PR
        if: success()
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const commentPath = 'pr_comment_body.txt';
            if (!fs.existsSync(commentPath)) {
              console.log("PR comment body not found. Skipping comment.");
              return;
            }

            const body = fs.readFileSync(commentPath, 'utf8').trim();
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body,
            });

      # - name: Update Flaky Tests in Google Sheets
      #   if: success()
      #   run: go run tools/update_flaky_tests/main.go
      #   env:
      #     GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Update Jira Tickets for Flaky Tests
        if: success()
        run: go run tools/update_jira_tickets/main.go
        env:
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
