name: Test with Flaky Report

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Install Dependencies
        run: go mod tidy

      - name: Install gotestsum
        run: go install gotest.tools/gotestsum@latest

      - name: Run Tests and Log Output
        run: |
          gotestsum \
          --format=github-actions \
          --rerun-fails --rerun-fails=10 --rerun-fails-max-failures=10 \
          --jsonfile='test_results.json' --junitfile='test_results.xml' \
          --packages="./..." -- -count=1

      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: |
            test_results.json
            test_results.xml

  flakytest:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Download Test Results
        uses: actions/download-artifact@v3
        with:
          name: test-results

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21
    
      - name: Check Failures in Test Results
        id: check_failures
        # This step checks the number of test failures from the XML file.
        # It ensures efficiency by reading only the first two lines of the file to extract the failure count.
        # This avoids unnecessary processing of the entire test result JSON if there are no failures.
        run: |
          failures=$(sed -n '2{p;q;}' test_results.xml | awk -F'"' '{print $4}')
          echo "Failures: $failures"
          echo "failures=$failures" >> $GITHUB_OUTPUT

      - name: Generate Flaky Report
        if: ${{ steps.check_failures.outputs.failures != '0' }}
        run: |
          go run tools/flaky_test/flaky_test_report_json/main.go < test_results.json > flaky_report.json

      - name: Generate PR Comment Body
        if: ${{ steps.check_failures.outputs.failures != '0' }}
        run: |
          go run tools/flaky_test/generate_pr_comment/main.go < flaky_report.json > flaky_comment_body.txt

      - name: Comment on PR
        if: ${{ steps.check_failures.outputs.failures != '0' }}
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const body = fs.readFileSync('flaky_comment_body.txt', 'utf8').trim();
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body,
            });

      # - name: Update Flaky Tests in Google Sheets
      #   if: success()
      #   run: go run tools/update_flaky_tests/main.go
      #   env:
      #     GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Update Jira Tickets for Flaky Tests
        if: ${{ steps.check_failures.outputs.failures != '0' }}
        run: go run tools/flaky_test/update_jira_tickets/main.go < flaky_report.json
        env:
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}