name: Test with Flaky Report

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Install Dependencies
        run: go mod tidy

      - name: Run Tests with gotestsum
        run: |
          go install gotest.tools/gotestsum@latest
          gotestsum \
          --rerun-fails --rerun-fails=10 --rerun-fails-max-failures=10 \
          --jsonfile test_results.json \
          --packages="./..."

      - name: Clean Go Module Cache
        run: go clean -modcache

      # - name: Install go-ctrf-json-reporter
      #   run: go install github.com/ctrf-io/go-ctrf-json-reporter/cmd/go-ctrf-json-reporter@latest
      # - name: Convert test_results.json to CTRF format
      #   run: go-ctrf-json-reporter < test_results.json

      # - name: Install go-ctrf-json-reporter
      #   run: |
      #     go install github.com/taman9333/go-ctrf-json-reporter/cmd/go-ctrf-json-reporter@main

      - name: Clone Modified go-ctrf-json-reporter
        run: |
          git clone https://github.com/taman9333/go-ctrf-json-reporter.git /tmp/go-ctrf-json-reporter
          cd /tmp/go-ctrf-json-reporter
          go mod tidy
          go build -o /usr/local/bin/go-ctrf-json-reporter ./cmd/go-ctrf-json-reporter

      - name: Convert test_results.json to CTRF format
        run: go-ctrf-json-reporter < test_results.json
      - uses: actions/setup-node@v4
        with:
          node-version: "18.x"
      - name: Upload ctrf report as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: ctrf-report
          path: ctrf-report.json
      # - name: Publish CTRF Flaky Rate Test Summary Results
      #   run: npx github-actions-ctrf flaky ctrf-report.json
      #   if: always()
      # - name: Publish CTRF Test Summary Results
      #   run: npx github-actions-ctrf ctrf-report.json
      #   if: always()
      - name: Publish CTRF pull request comment
        run: npx github-actions-ctrf pull-request ctrf-report.json
        if: always()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Post PR Comment
        run: npx github-actions-ctrf flaky ctrf-report.json --pull-request
        if: always()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Post PR Comment
        run: npx github-actions-ctrf flaky-rate ctrf-report.json --pull-request
        if: always()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}